"""add_scrape_and_mail_logs

Revision ID: c81c000ff360
Revises: a1b2c3d4e5f6
Create Date: 2025-11-25 20:47:17.294416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81c000ff360'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('subscribed_total', sa.Integer(), nullable=False),
    sa.Column('subscribed_sent', sa.Integer(), nullable=False),
    sa.Column('subscribed_failed', sa.Integer(), nullable=False),
    sa.Column('subscribed_skipped', sa.Integer(), nullable=False),
    sa.Column('subscribed_errors', sa.JSON(), nullable=True),
    sa.Column('expired_total', sa.Integer(), nullable=False),
    sa.Column('expired_sent', sa.Integer(), nullable=False),
    sa.Column('expired_failed', sa.Integer(), nullable=False),
    sa.Column('expired_errors', sa.JSON(), nullable=True),
    sa.Column('never_subscribed_total', sa.Integer(), nullable=False),
    sa.Column('never_subscribed_sent', sa.Integer(), nullable=False),
    sa.Column('never_subscribed_failed', sa.Integer(), nullable=False),
    sa.Column('never_subscribed_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('duration_millis', sa.Integer(), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('successful_scrapes', sa.Integer(), nullable=False),
    sa.Column('failed_scrapes', sa.Integer(), nullable=False),
    sa.Column('total_offers_scraped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_logs')
    op.drop_table('mail_logs')
    # ### end Alembic commands ###
