"""add deduplicate offert logic

Revision ID: 72874ec45977
Revises: 21c28e49df14
Create Date: 2025-12-16 13:21:09.055118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72874ec45977'
down_revision = '21c28e49df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_duplicate_offers', sa.Boolean(), nullable=True))

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('ix_offers_url', ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offers_url')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('allow_duplicate_offers')

    # ### end Alembic commands ###
