"""Change email body to text

Revision ID: 39f92d1182ee
Revises: 05b5c3955608
Create Date: 2025-11-24 14:10:13.136842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f92d1182ee'
down_revision = '05b5c3955608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_offer_emails', schema=None) as batch_op:
        batch_op.alter_column('email_body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_offer_emails', schema=None) as batch_op:
        batch_op.alter_column('email_body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
