"""Add scoring and OpenAI settings

Revision ID: bbea275c3671
Revises: a1b2c3d4e5f7
Create Date: 2025-12-12 11:03:25.409596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbea275c3671'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('openai_scoring_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_must_contain', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('test_may_contain', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('test_must_not_contain', sa.JSON(), nullable=True))

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fit_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attractiveness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('overall_score')
        batch_op.drop_column('attractiveness_score')
        batch_op.drop_column('fit_score')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('test_must_not_contain')
        batch_op.drop_column('test_may_contain')
        batch_op.drop_column('test_must_contain')
        batch_op.drop_column('openai_scoring_prompt')
        batch_op.drop_column('openai_api_key')

    # ### end Alembic commands ###
