"""Remove including_keyword from offer model

Revision ID: d9febf5d128c
Revises: eacdc6af92ee
Create Date: 2025-11-25 01:34:01.228398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9febf5d128c'
down_revision = 'eacdc6af92ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('including_keyword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('including_keyword', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
