"""add_scrape_running_state

Revision ID: 21c28e49df14
Revises: bbea275c3671
Create Date: 2025-12-12 22:35:28.645851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c28e49df14'
down_revision = 'bbea275c3671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_scrape_running', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('scrape_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('scrape_started_at')
        batch_op.drop_column('is_scrape_running')

    # ### end Alembic commands ###
