"""add max offers options

Revision ID: 65c0c10ddc9f
Revises: 72874ec45977
Create Date: 2025-12-16 17:51:17.249912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c0c10ddc9f'
down_revision = '72874ec45977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_max_offers', sa.JSON(), nullable=True))
        batch_op.drop_column('upwork_max_offers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upwork_max_offers', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True))
        batch_op.drop_column('platform_max_offers')

    # ### end Alembic commands ###
