"""Improve user related objects

Revision ID: eb502efc8801
Revises: 3963c6cb839d
Create Date: 2025-11-16 18:48:15.985934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb502efc8801'
down_revision = '3963c6cb839d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_offer_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('must_include_keywords', sa.JSON(), nullable=True),
    sa.Column('can_include_keywords', sa.JSON(), nullable=True),
    sa.Column('cannot_include_keywords', sa.JSON(), nullable=True),
    sa.Column('email_sent_to', sa.String(), nullable=True),
    sa.Column('email_title', sa.String(), nullable=True),
    sa.Column('email_body', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_offer_topic_preferences')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_offer_email_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('including_keyword', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user_offer_emails', ['user_offer_email_id'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('specific_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specific_category', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('including_keyword')
        batch_op.drop_column('user_offer_email_id')

    op.create_table('user_offer_topic_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_offer_topic_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_offer_topic_preferences_pkey'))
    )
    op.drop_table('user_offer_emails')
    # ### end Alembic commands ###
