"""Add shuffle keywords option

Revision ID: a40e54347d69
Revises: cae37a7e612e
Create Date: 2025-12-16 23:24:40.280323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40e54347d69'
down_revision = 'cae37a7e612e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuffle_keywords', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('shuffle_keywords')

    # ### end Alembic commands ###
