"""Add min score thresholds

Revision ID: cae37a7e612e
Revises: 65c0c10ddc9f
Create Date: 2025-12-16 23:16:15.709157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae37a7e612e'
down_revision = '65c0c10ddc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_fit_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_attractiveness_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('min_attractiveness_score')
        batch_op.drop_column('min_fit_score')

    # ### end Alembic commands ###
