"""Add WorkConnect cache and settings

Revision ID: 308c4f55e4f0
Revises: a40e54347d69
Create Date: 2025-12-18 22:04:40.390459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308c4f55e4f0'
down_revision = 'a40e54347d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_offers', schema=None) as batch_op:
        batch_op.create_index('ix_cached_offers_platform', ['platform'], unique=False)
        batch_op.create_index('ix_cached_offers_url', ['url'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workconnect_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('workconnect_mock_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('workconnect_cache_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('workconnect_max_offers', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('workconnect_max_offers')
        batch_op.drop_column('workconnect_cache_hours')
        batch_op.drop_column('workconnect_mock_enabled')
        batch_op.drop_column('workconnect_enabled')

    with op.batch_alter_table('cached_offers', schema=None) as batch_op:
        batch_op.drop_index('ix_cached_offers_url')
        batch_op.drop_index('ix_cached_offers_platform')

    op.drop_table('cached_offers')
    # ### end Alembic commands ###
