"""Add client_name

Revision ID: d17928aa96f4
Revises: 366c24b0151e
Create Date: 2025-11-12 14:05:05.189153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17928aa96f4'
down_revision = '366c24b0151e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('specific_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('specific_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
