"""Add preferences and unsubscribe tokens

Revision ID: cdeb1ed4741e
Revises: eb502efc8801
Create Date: 2025-11-18 17:30:30.311596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdeb1ed4741e'
down_revision = 'eb502efc8801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_email_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_preferences_token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email_unsubscribe_token', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email_unsubscribe_token'])
        batch_op.create_unique_constraint(None, ['email_preferences_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_unsubscribe_token')
        batch_op.drop_column('email_preferences_token')

    with op.batch_alter_table('user_email_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
