"""Extend offer object

Revision ID: 366c24b0151e
Revises: 31d97f90ff0d
Create Date: 2025-11-10 21:58:47.393199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '366c24b0151e'
down_revision = '31d97f90ff0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('specific_category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.String(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('topic')

    with op.batch_alter_table('user_offer_topic_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.JSON(), nullable=True))
        batch_op.drop_column('topics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_offer_topic_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('categories')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('budget')
        batch_op.drop_column('specific_category')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
