"""Change config to app settings

Revision ID: 05b5c3955608
Revises: cdeb1ed4741e
Create Date: 2025-11-18 22:34:06.911050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05b5c3955608'
down_revision = 'cdeb1ed4741e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled_platforms', sa.JSON(), nullable=True),
    sa.Column('email_frequency', sa.String(), nullable=True),
    sa.Column('email_daytime', sa.String(), nullable=True),
    sa.Column('email_max_offers', sa.Integer(), nullable=True),
    sa.Column('mail_api_key', sa.String(), nullable=True),
    sa.Column('mail_sender_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('configs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('configs_pkey'))
    )
    op.drop_table('app_settings')
    # ### end Alembic commands ###
