"""Add offer bundle logic

Revision ID: 843f0f9b020e
Revises: f3a8b9c2d1e4
Create Date: 2025-11-25 00:31:18.920919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843f0f9b020e'
down_revision = 'f3a8b9c2d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_bundles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_offer_email_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_bundle_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('offers_user_offer_email_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'offer_bundles', ['offer_bundle_id'], ['id'])
        batch_op.drop_column('user_offer_email_id')

    with op.batch_alter_table('user_offer_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_bundle_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_offer_emails', schema=None) as batch_op:
        batch_op.drop_column('offer_bundle_id')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_offer_email_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('offers_user_offer_email_id_fkey'), 'user_offer_emails', ['user_offer_email_id'], ['id'])
        batch_op.drop_column('offer_bundle_id')

    op.drop_table('offer_bundles')
    # ### end Alembic commands ###
