"""add duration to bundle

Revision ID: fa605dbd6b3d
Revises: 0f46ecf167a9
Create Date: 2025-11-25 02:00:01.426939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa605dbd6b3d'
down_revision = '0f46ecf167a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrape_duration_millis', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_bundles', schema=None) as batch_op:
        batch_op.drop_column('scrape_duration_millis')

    # ### end Alembic commands ###
