"""Add apify_api_key to app_settings

Revision ID: f3a8b9c2d1e4
Revises: 39f92d1182ee
Create Date: 2025-11-24 16:04:18.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a8b9c2d1e4'
down_revision = '39f92d1182ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apify_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('apify_api_key')

    # ### end Alembic commands ###

