"""Change keywords from mail to bundle

Revision ID: eacdc6af92ee
Revises: 843f0f9b020e
Create Date: 2025-11-25 01:28:21.511793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eacdc6af92ee'
down_revision = '843f0f9b020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_include_keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('can_include_keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cannot_include_keywords', sa.JSON(), nullable=True))

    with op.batch_alter_table('user_offer_emails', schema=None) as batch_op:
        batch_op.drop_column('can_include_keywords')
        batch_op.drop_column('cannot_include_keywords')
        batch_op.drop_column('must_include_keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_offer_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_include_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cannot_include_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_include_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('offer_bundles', schema=None) as batch_op:
        batch_op.drop_column('cannot_include_keywords')
        batch_op.drop_column('can_include_keywords')
        batch_op.drop_column('must_include_keywords')

    # ### end Alembic commands ###
