"""add cancelled_at to offer_bundles and scrape_hours_before to app_settings

Revision ID: 9eeba47c1867
Revises: 308c4f55e4f0
Create Date: 2026-03-31 18:30:28.051985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eeba47c1867'
down_revision = '308c4f55e4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scrape_hours_before', sa.Integer(), nullable=True))

    with op.batch_alter_table('offer_bundles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_bundles', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('scrape_hours_before')

    # ### end Alembic commands ###
